openapi: 3.0.3

info:
  version: 1.0.0
  title: ISA Returns Test Support API
  description: |
    # Overview
    Use this API to trigger the generation of a test reconciliation report for the ISA Returns API. 
    It supports integration testing of reconciliation handling in the sandbox environment.

    # Integration requirements
    - REST API using JSON over HTTPS.
    - Authentication uses the OAuth 2.0 client credentials grant.
    - All API calls require a unique identifier (Z-Reference) assigned by HMRC to each approved ISA manager.

    # Support
    If you need help, complete the [support form](https://developer.service.hmrc.gov.uk/developer/support). 
    HMRC's Software Developers Support Team will reply within two working days. 

servers:
  - url: https://test-api.service.hmrc.gov.uk/test/obligations/declaration/isa/return
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/test/obligations/declaration/isa/return
    description: Production

tags:
  - name: Test reconciliation
    description: |
      Generate test reconciliation reports for the ISA Returns API to support integration testing in the sandbox environment.

#      Open Question - since we can reasonably assume they might want to be more specific, what does that endpoint look like?

paths:
  /monthly/{zReference}/{taxYear}/{month}/reconciliation:
    post:
      summary: Generate test reconciliation report
      description: |
        Use this endpoint to trigger the generation of a test reconciliation report for the ISA Returns API.

        You can specify how many simulated errors to include in each category:
          - oversubscriptions
          - trace and match failures
          - eligibility failures

        The reconciliation report is not returned directly. 
        Instead, a monthly return summary and reconciliation report are made available to the ISA Returns API, 
        and a push-pull notification (PPNS) is triggered.
        
        Note: Each reconciliation report generation is limited to a maximum of 2,000 issues across all issue types per Z-reference, tax year, and month. Attempts to exceed this limit will result in an error.
      operationId: generateTestReconciliationReport
      tags:
        - Test reconciliation
      security:
        - userRestricted:
            - write:isa-returns
      parameters:
        - name: zReference
          in: path
          description: |
            A unique identifier assigned by HMRC to each approved ISA manager. Format: 'Zxxxx'.
          required: true
          style: simple
          explode: false
          schema:
            pattern: ^[z|Z][0-9]{4}$
            type: string
            example: Z1234
        - name: taxYear
          in: path
          description: |
            Tax year of the report.
          required: true
          style: simple
          explode: false
          schema:
            pattern: ^20\d{2}-\d{2}$
            format: string
            example: 2025-26
        - name: month
          in: path
          description: |
            Month of the report.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: APR
            enum:
              - JAN
              - FEB
              - MAR
              - APR
              - MAY
              - JUN
              - JUL
              - AUG
              - SEP
              - OCT
              - NOV
              - DEC
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/reportDescriptionSimple'
      responses:
        204:
          description: Submission accepted. No content returned.
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/badSubmissionGeneral'
                  - $ref: '#/components/schemas/badRequestParametersMultipleErrors'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    title: Error Code Type
                    type: string
                    description: Error Code
                    enum:
                      - UNAUTHORIZED
                  message:
                    type: string
                    example: Unauthorized
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    title: Error Code Type
                    type: string
                    description: Error Code
                    enum:
                      - INTERNAL_SERVER_ERROR
                  message:
                    type: string
                    example: "There has been an issue processing your request"
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC uses OAuth 2.0 Bearer tokens for authentication. Include the token in the AUTHORIZATION header of user-restricted API requests.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes: {
            "write:isa-returns": "submit data to the api",
          }
  parameters:
    acceptHeader:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json"
        ]
    authorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      description: Bearer token for authentication.
  schemas:
    reportDescriptionSimple:
      title: Report Description (Simple)
      type: object
      required: [oversubscribed, traceAndMatch, failedEligibility]
      properties:
        oversubscribed:
          type: number
          description: Number of simulated oversubscription errors to include in the callback.
          pattern: $\d^
        traceAndMatch:
          type: number
          description: Number of simulated trace and match errors to include in the callback.
          pattern: $\d^
        failedEligibility:
          type: number
          description: Number of simulated eligibility errors to include in the callback.
          pattern: $\d^
    badSubmissionGeneral:
      title: Bad Request (General Issue)
      type: object
      properties:
        code:
          title: Validation Failure Code
          type: string
          description: Code indicating the type of error.
          enum:
            - INVALID_TAX_YEAR
            - INVALID_MONTH
            - INVALID_Z_REFERENCE
            - MALFORMED_JSON
            - EMPTY_PAYLOAD
            - ISSUE_LIMIT_EXCEEDED
        message:
          title: Detailed Message
          type: string
          description: Message describing the details of the validation error.
      example:
        code: EMPTY_PAYLOAD
        message: "The payload is empty. Please ensure the request body contains a valid JSON payload before resubmitting."
    invalidTaxYear:
      title: Invalid Tax Year
      type: object
      properties:
        code:
          type: string
          description: Code indicating the type of error.
          enum:
            - INVALID_TAX_YEAR
        message:
          title: Message
          type: string
          description: Human-readable message outlining the error.
          example: "Invalid tax year provided"
    invalidMonth:
      title: Invalid Month
      type: object
      properties:
        code:
          type: string
          description: Code indicating the type of error.
          enum:
            - INVALID_MONTH
        message:
          title: Message
          type: string
          description: Human-readable message outlining the error.
          example: "Invalid month provided"
    invalidZReference:
      title: Invalid Z-Reference
      type: object
      properties:
        code:
          type: string
          description: Code indicating the type of error.
          enum:
            - INVALID_Z_REFERENCE
        message:
          title: Message
          type: string
          description: Human-readable message outlining the error.
          example: "Invalid z-reference provided"
    badRequestParametersMultipleErrors:
      title: Bad Request Parameters (Multiple Errors)
      type: object
      properties:
        code:
          title: Error Code Type
          type: string
          description: Code indicating the type of error.
          enum:
            - BAD_REQUEST
        message:
          title: Message
          type: string
          description: Human-readable message outlining the error.
          example: "Multiple issues found regarding your submission"
        errors:
          title: Errors
          type: array
          description: Array of errors outlining issues found regarding your submission.
          items:
            anyOf:
              - $ref: '#/components/schemas/invalidTaxYear'
              - $ref: '#/components/schemas/invalidMonth'
              - $ref: '#/components/schemas/invalidZReference'
          example:
            - code: INVALID_TAX_YEAR
              message: Invalid tax year provided
            - code: INVALID_MONTH
              message: Invalid month provided